### PR TITLE
implement todo

### PR DESCRIPTION
**Pull request by bmusin**
1. TODO: Changed tokenize to use iterator, not slice.
2. Added few tests(float arithmetic).
3. Implemented Display, so to_string() is available.
4. Formatting fixes with rustfmt-nightly.

### CODE REVIEW

**Comment by jackpot51** [comment]
You may want to do these changes against this codebase: https://github.com/redox-os/calc

And then port this calc to use the library instead.

**Comment by bltnkl** [comment]
Why do you maintain separate implementations of calc in extrautils and calc?

**Comment by jackpot51** [comment]
We don't. It was supposed to be replaced with the seperate library, which is a copy of this code. The library is being used in `orbutils` and `ion`, and should also be used here.

**Comment by bltnkl** [comment]
What about copying from calc repo to here?

**Pull request closed without merging**
